### ISSUE TITLE
Wrong color HEX codes

### ISSUE THREAD

**Issue by algo99** [usernamehw/vscode-theme-prism#1]
Hi,

by the way thank you for your effort, I find the Prism theme is really great.

By inspecting the `Prism-color-theme-minimized.json` file i found groups of 4 and 8 digits. Not sure how VSCode interpret them but should it be only groups of 3 and 6 digits anyway ?

# 4 digits:
"editorBracketMatch.border": "#fff0",
"editorBracketMatch.background": "#07a3",
"extensionButton.prominentHoverBackground": "#690b",
"statusBar.debuggingBackground": "#e907",

# 8 digits
"editorLineNumber.foreground": "#70809060",
"editor.lineHighlightBackground": "#70809025",
"statusBarItem.hoverBackground": "#70809050",
"diffEditor.insertedTextBackground": "#66990030",
"diffEditor.removedTextBackground": "#dd4a6830",
"scope": "invalid.deprecated",
            "settings":
            {
                "foreground": "#96000060"
            }

**Comment by usernamehw** [comment]
vscode supports 4 & 8 digit color https://code.visualstudio.com/api/references/theme-color#color-formats

It is planned for CSS4 to support them https://caniuse.com/#feat=css-rrggbbaa

`#fff0` - 0 - is transparency (in HEX)
`#ffffff00` - 00 - is transparency (in HEX)

But I should probably review them anyway.

**Comment by algo99** [comment]
Thank you for the VSCode link,  somehow missed it.
