### ISSUE TITLE
Add a License to your VS Code Extension

### ISSUE THREAD

**Issue by spoenemann** [usernamehw/vscode-theme-prism#2]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please add a license to your extension and upload a new version **as early as possible before January 15, 2021**. To include a license with the extension, add a `license` field with the license identifier in the package.json and add a LICENSE file with the full license text. If you are unsure which license to choose, check the [list of OSI-approved licenses](https://opensource.org/licenses).

Regrettably if this is not done by that date, extension versions that have no license will be deleted. Of course you can publish them again with a license at a later date.

Please note, the latest version of the `ovsx` tool offers to add the MIT license when you try to publish without a license.

A reminder  that all extension publishers MUST sign the Eclipse Publisher Agreement.

Useful links:
[Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)
[Eclipse Foundation Open VSX Registry Frequently Asked Questions (FAQ)](https://www.eclipse.org/legal/open-vsx-registry-faq/) 

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

**Comment by spoenemann** [comment]
@usernamehw thanks for responding!

Could you publish a new version of your extension to open-vsx.org? We will have to delete the older version because of the missing license.

**Comment by usernamehw** [comment]
@spoenemann Is this message for extension version `1.0.0`? [1.0.1](https://open-vsx.org/extension/usernamehw/prism) should have license and be published.

**Comment by spoenemann** [comment]
Oh I see, great! :+1:
